# Generated by Django 2.2.6 on 2019-12-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='demon',
            name='sins',
            field=models.ManyToManyField(to='main_app.Sin'),
        ),
    ]
