# Generated by Django 2.2.6 on 2019-12-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191217_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sin',
            name='level',
        ),
    ]
