# Generated by Django 2.2.6 on 2019-12-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_sin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='sin',
            name='level',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
